### ISSUE TITLE
1.9.2  起不来

### ISSUE THREAD

**Issue by jjxutj** [aliyun-node/agenthub#5]
需要 监控 node 4.x 版本的 项目 因node是4.x 导致agenthub 起不来报错

/home/taomee61/.tnvm/versions/alinode/v1.9.2/lib/node_modules/@alicloud/agenthub/bin/agenthub:152
    const [appid, pid, config, startTime] = line.split(SPLITTER);
          ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1045:3

**Comment by zhangzifa** [comment]
@jjxutj 你们项目能升级到6.x/8.x吗？
4.x 社区到 2018-04-30后就停止维护了。

如果实在升级困难，我们会做一下兼容

**Comment by jjxutj** [comment]
公司老项目 没人去升级了 新项目已经到 8.x了  停止维护 没关系老项目 问题不大
今天我们的新项目已经用你们的 性能平台监测了。 感谢大阿里！！！！！！！！！！！！！！

**Comment by JacksonTian** [comment]
4.x 升级到 6.x 理论上来说 不会有 break change 的，你可以试试看。
